/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WeatherWear;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.aksingh.owmjapis.core.OWM;
import net.aksingh.owmjapis.api.APIException;
import net.aksingh.owmjapis.model.CurrentWeather;

/**
 *
 * @author sdzar
 */
public class WeatherWearGUI extends javax.swing.JFrame implements UnitsConversion{

    /**
     * Creates new form WeatherWearGUI
     */
    private final String KEY = "156b77ca1f98f37be98062d7f5379f6b";
    OWM owm = new OWM(KEY);
    static boolean maximized = true;
    static ImageIcon ii;
    Location WestLafayette = new Location("US", "IN", new City("West Lafayette", 4928096, "47906"));
    Location Indianapolis = new Location("US", "IN", new City("Indianapolis", 4259418, "46201"));
    Location Chicago = new Location("US", "IL", new City("Chicago", 4887398, "60007"));
    Location LosAngeles = new Location("US", "CA", new City("Los Angeles", 5344994, "91001"));
    Location Paris = new Location("FR", "IN", new City("Paris", 6269531, "75000"));
    Location Kathmandu = new Location("NP", "Province No. 3", new City("Kathmandu", 1283240, "44600"));
    Location city;
    Weather weather = new Weather();
    Precipitation precipitation;
    Rain rain;
    Snow snow;
    Drizzle drizzle;
    Thunderstorm thunderstorm;
    Atmosphere atmosphere;
    Wind wind;
    Clothing cloth;
    Clouds clouds;
    Extreme extreme;
    Date date;
    Calendar calendar = Calendar.getInstance();
    SimpleDateFormat formatter;
    
    public WeatherWearGUI() throws APIException, IOException {
        initComponents();
        getWeatherData(4928096);
        setWeatherData(WestLafayette);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        maximizer = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        City = new javax.swing.JLabel();
        DateTime = new javax.swing.JLabel();
        TempMM = new javax.swing.JLabel();
        Temp = new javax.swing.JLabel();
        HumidityLabel = new javax.swing.JLabel();
        Humidity = new javax.swing.JLabel();
        PressureLabel = new javax.swing.JLabel();
        Pressure = new javax.swing.JLabel();
        ICON = new javax.swing.JLabel();
        WindLabel = new javax.swing.JLabel();
        Wind = new javax.swing.JLabel();
        Main = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        Precipitation = new javax.swing.JLabel();
        PrecipitationLabel = new javax.swing.JLabel();
        ClothingLabel = new javax.swing.JLabel();
        Clothing = new javax.swing.JLabel();
        DateTimeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        close.setIcon(new ImageIcon(getClass().getResource("/cancel.png")));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        maximizer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximizer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximize.png"))); // NOI18N
        maximizer.setIcon(new ImageIcon(getClass().getResource("/maximize.png")));
        maximizer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizerMouseClicked(evt);
            }
        });

        title.setBackground(new java.awt.Color(204, 153, 0));
        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(204, 153, 0));
        title.setText("Weather Wear");

        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N

        searchTextField.setBackground(new java.awt.Color(0, 0, 0));
        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchTextField.setBorder(null);
        AutoSuggestor autoSuggestor = new AutoSuggestor(searchTextField, WeatherWearGUI.this, null, Color.WHITE, Color.BLACK, Color.RED, 1.0f) {
            @Override
            boolean wordTyped(String typedWord) {
                //create list for dictionary this in your case might be done via calling a method which queries db and returns results as arraylist
                ArrayList<String> words = new ArrayList<>();
                words.add("West Lafayette");
                words.add("Indianapolis");
                words.add("Chicago");
                words.add("Los Angeles");
                words.add("Paris");
                words.add("Kathmandu");

                setDictionary(words);
                //addToDictionary("bye");//adds a single word
                return super.wordTyped(typedWord);//now call super to check for any matches against newest dictionary
            }
        };
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(maximizer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maximizer)
                            .addComponent(close))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(title))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));

        City.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        City.setText("City");

        DateTime.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        DateTime.setText("DateTime");

        TempMM.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TempMM.setText("TempMax TempMin");

        Temp.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Temp.setText("Temp");

        HumidityLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        HumidityLabel.setText("Humidity ");

        Humidity.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Humidity.setText("Humidity");

        PressureLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        PressureLabel.setText("Pressure");

        Pressure.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Pressure.setText("Pressure");

        ICON.setMaximumSize(new java.awt.Dimension(100, 100));
        ICON.setMinimumSize(new java.awt.Dimension(100, 100));
        ICON.setName(""); // NOI18N
        ICON.setPreferredSize(new java.awt.Dimension(100, 100));

        WindLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        WindLabel.setText("Wind");

        Wind.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Wind.setText("Wind");

        Main.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Main.setText("Main");

        F.setBackground(new java.awt.Color(255, 255, 255));
        F.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        F.setText("F");
        F.setText("\u00b0F");
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
        });

        C.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        C.setText("C");
        C.setText("\u00b0C");
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });

        Precipitation.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Precipitation.setText("Precipitation");

        PrecipitationLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        PrecipitationLabel.setText("Precipitation");

        ClothingLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ClothingLabel.setText("Clothing Suggestion");

        Clothing.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Clothing.setText("Clothing");

        DateTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        DateTimeLabel.setText("Updated at:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(City)
                    .addComponent(Main)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Temp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TempMM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PressureLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(HumidityLabel)
                                    .addGap(58, 58, 58)))
                            .addComponent(WindLabel)
                            .addComponent(PrecipitationLabel))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Precipitation)
                            .addComponent(Wind)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Humidity)
                                    .addComponent(Pressure))
                                .addGap(158, 158, 158)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClothingLabel)
                                    .addComponent(Clothing)
                                    .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(DateTimeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateTime)
                    .addComponent(DateTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TempMM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Main)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Temp)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(C)
                                .addComponent(F)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HumidityLabel)
                            .addComponent(Humidity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PressureLabel)
                            .addComponent(Pressure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WindLabel)
                            .addComponent(Wind))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecipitationLabel)
                            .addComponent(Precipitation)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClothingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clothing)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /*
    * This method is used to get all the data via the API and save them to the local objects
    */
    public void getWeatherData(int id) throws APIException {
        CurrentWeather cwd = owm.currentWeatherByCityId(id);
        date = cwd.getDateTime();
        calendar.setTime(date);
        System.out.println(cwd.getWeatherList().get(0).getConditionId());
        weather.setId(cwd.getWeatherList().get(0).getConditionId());
        weather.setMain(cwd.getWeatherList().get(0).getMainInfo());
        weather.setDescription(cwd.getWeatherList().get(0).getDescription());
        weather.setIcon(cwd.getWeatherList().get(0).getIconLink());
        weather.setHumidity(cwd.getMainData().getHumidity());
        weather.setPressure(cwd.getMainData().getPressure());
        weather.setTemp(cwd.getMainData().getTemp());
        weather.setTemp_max(cwd.getMainData().getTempMax());
        weather.setTemp_min(cwd.getMainData().getTempMin());
        weather.setWind(new Wind(cwd.getWindData().getSpeed(), cwd.getWindData().getDegree()));
        wind = weather.getWind();
        cloth = new Clothing();
        cloth.setClothing(weather.getTemp());
        cloth.setAccessory(weather.getId() < 600);
        
        precipitation = new Precipitation(0,weather);
        if (weather.getId() < 300) {
            if (cwd.getRainData() != null)
                precipitation.setPrecAmt(cwd.getRainData().getPrecipVol3h());
            thunderstorm = new Thunderstorm(precipitation, weather);
        } else if (weather.getId() < 400) {
            if (cwd.getRainData() != null)
                precipitation.setPrecAmt(cwd.getRainData().getPrecipVol3h());
            drizzle = new Drizzle(precipitation, weather);
        } else if (weather.getId() <  600) {
            if (cwd.getRainData() != null)
                precipitation.setPrecAmt(cwd.getRainData().getPrecipVol3h());
            rain = new Rain(precipitation, weather);
        } else if (weather.getId() < 700) {
            precipitation = new Precipitation(weather);
            precipitation.setPrecAmt(cwd.getSnowData().getSnowVol3h());
            snow = new Snow(precipitation, weather);
        } else if (weather.getId() < 800) {
            atmosphere = new Atmosphere(weather);
        } else if (weather.getId() < 900) {
            clouds = new Clouds(cwd.getCloudData().getCloud(), weather);
        } else {
            extreme = new Extreme(weather);
        }
    }
   /*
    * This method is used to display all the data which saved in objects on the GUI
    */
    public void setWeatherData(Location city) throws MalformedURLException, IOException {
        URL url = new URL(weather.getIcon());
        BufferedImage image = ImageIO.read(url);
        BufferedImage resized = resize(image, 100, 100);
        City.setText(city.getCity().getCity());
        TempMM.setText("High " + String.format("%.0f", kToF(weather.getTemp_max())) + "\u00b0 / Low " + String.format("%.0f", kToF(weather.getTemp_min())) + "\u00b0");
        Temp.setText(String.format("%.0f", kToF(weather.getTemp())) + "\u00b0");
        Humidity.setText(String.valueOf(weather.getHumidity()) + "%");
        Pressure.setText(String.valueOf(weather.getPressure()) + " hPa");
        formatter = new SimpleDateFormat("MMMM dd hh:mm z");
        DateTime.setText(formatter.format(calendar.getTime()));
        Wind.setText(String.format("%.0f", wind.getWindSpeedMph()) + " mph " + wind.getWindDirection());
        Main.setText(weather.getMain());
        Precipitation.setText(String.format("%.0f", precipitation.getPrecAmt()) + " mm");
        Clothing.setText(cloth.getClothing());
        ICON.setIcon(new ImageIcon(resized));
    }
   /*
    * This method is used to resize the .png image I get online
    */
    private static BufferedImage resize(BufferedImage img, int height, int width) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }
        
    int xy;
    int xx;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void maximizerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizerMouseClicked
        if(maximized) {
            //handle fullscreen - taskbar
            WeatherWearGUI.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            WeatherWearGUI.this.setMaximizedBounds(env.getMaximumWindowBounds());
            ii = new ImageIcon(getClass().getResource("/minimize.png"));
            maximizer.setIcon(ii);
            maximized = false;
        }
        else {
            setExtendedState(JFrame.NORMAL);
            ii = new ImageIcon(getClass().getResource("/maximize.png"));
            maximizer.setIcon(ii);
            maximized = true;
        }
    }//GEN-LAST:event_maximizerMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        try {
            if (searchTextField.getText().trim().equalsIgnoreCase("West Lafayette")) {
                getWeatherData(WestLafayette.getCity().getID());
                setWeatherData(WestLafayette);
            } else if (searchTextField.getText().trim().equalsIgnoreCase("Indianapolis")) {
                getWeatherData(Indianapolis.getCity().getID());
                setWeatherData(Indianapolis);
            } else if (searchTextField.getText().trim().equalsIgnoreCase("Chicago")) {
                getWeatherData(Chicago.getCity().getID());
                setWeatherData(Chicago);
            } else if (searchTextField.getText().trim().equalsIgnoreCase("Los Angeles")) {
                getWeatherData(LosAngeles.getCity().getID());
                setWeatherData(LosAngeles);
            } else if (searchTextField.getText().trim().equalsIgnoreCase("Paris")) {
                getWeatherData(Paris.getCity().getID());
                setWeatherData(Paris);
            } else if (searchTextField.getText().trim().equalsIgnoreCase("Kathmandu")) {
                getWeatherData(Kathmandu.getCity().getID());
                setWeatherData(Kathmandu);
            }
        } catch (IOException ex) {
            Logger.getLogger(WeatherWearGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (APIException ex) {
            Logger.getLogger(WeatherWearGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
        F.setFont(new java.awt.Font("Segoe UI", 1, 13));
        C.setFont(new java.awt.Font("Segoe UI", 0, 13));
        TempMM.setText("High " + String.format("%.0f", kToF(weather.getTemp_max())) + "\u00b0 / Low " + String.format("%.0f", kToF(weather.getTemp_min())) + "\u00b0");
        Temp.setText(String.format("%.0f", kToF(weather.getTemp())) + "\u00b0");
    }//GEN-LAST:event_FMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
        C.setFont(new java.awt.Font("Segoe UI", 1, 13));
        F.setFont(new java.awt.Font("Segoe UI", 0, 13));
        TempMM.setText("High " + String.format("%.0f", kToC(weather.getTemp_max())) + "\u00b0 / Low " + String.format("%.0f", kToC(weather.getTemp_min())) + "\u00b0");
        Temp.setText(String.format("%.0f", kToC(weather.getTemp())) + "\u00b0");
    }//GEN-LAST:event_CMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws APIException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherWearGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherWearGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherWearGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherWearGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        WeatherWearGUI gui = new WeatherWearGUI();
        gui.setTitle("WeatherWear");
        gui.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C;
    private javax.swing.JLabel City;
    private javax.swing.JLabel Clothing;
    private javax.swing.JLabel ClothingLabel;
    private javax.swing.JLabel DateTime;
    private javax.swing.JLabel DateTimeLabel;
    private javax.swing.JLabel F;
    private javax.swing.JLabel Humidity;
    private javax.swing.JLabel HumidityLabel;
    private javax.swing.JLabel ICON;
    private javax.swing.JLabel Main;
    private javax.swing.JLabel Precipitation;
    private javax.swing.JLabel PrecipitationLabel;
    private javax.swing.JLabel Pressure;
    private javax.swing.JLabel PressureLabel;
    private javax.swing.JLabel Temp;
    private javax.swing.JLabel TempMM;
    private javax.swing.JLabel Wind;
    private javax.swing.JLabel WindLabel;
    private javax.swing.JLabel close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maximizer;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    @Override
    public double kToC(double i) {
        return i - 273.15;
    }

    @Override
    public double kToF(double i) {
        return i * 9 / 5 - 459.67;
    }
}
